---
  :name: Katello devel
  :description:
  :log_dir: /var/log/foreman-installer
  :log_name: katello-devel-installer.log
  :log_level: DEBUG
  :no_prefix: true
  :answer_file: "./config/katello-devel-answers.yaml"
  :installer_dir: "."
  :default_values_dir: "/tmp"
  :module_dirs: ["./_build/modules", "../katello-installer/modules"]
  :hook_dirs: ["../katello-installer/hooks"]

  :colors: true
  :order:
    - certs
    - katello_devel
    - foreman_proxy
  :password: l7VtnWiPeKe412o2CVBM6yVbTkKGh6L_CKx4_zBkmUE

  :mapping:
    :katello_devel::plugin::gutterball:
      :dir_name: katello_devel
      :manifest_name: plugin/gutterball
    :katello_devel::plugin::foreman_gutterball:
      :dir_name: katello_devel
      :manifest_name: plugin/foreman_gutterball
    :foreman_proxy::plugin::pulp:
      :manifest_name: plugin/pulp
      :params_name: plugin/pulp/params
      :dir_name: foreman_proxy
